%import common.NEWLINE
%ignore /[ \t\r]+/

_NL:    NEWLINE
_DELIM: "·" | "|"

// ─── ENTRY ───────────────────────────────────────────────────────────────────

unit: phrase | statement

// ─── STATEMENT ───────────────────────────────────────────────────────────────

statement: header item+

// ─── PHRASE ──────────────────────────────────────────────────────────────────

phrase:  header modifier* (_NL modifier+)* score
score:   (_DELIM | _NL) quality ((_DELIM | _NL) quality)*
quality: item+

// ─── HEADER ──────────────────────────────────────────────────────────────────

header: "@" NAME

// ─── MODIFIERS ───────────────────────────────────────────────────────────────

modifier: dot_mod | colon_mod

dot_mod:   "." NAME array?
colon_mod: ":" NAME array?

// ─── ARRAY ───────────────────────────────────────────────────────────────────

array: "(" item* ")"
		| "{" item* "}"

// ─── ITEM ────────────────────────────────────────────────────────────────────

item: FUNC array   -> func
    | VALUE        -> atom
    | array        -> atom

// ─── TOKENS ──────────────────────────────────────────────────────────────────

NAME:  /[a-zA-Z_][a-zA-Z0-9_]*/
FUNC:  /[a-zA-Z_][a-zA-Z0-9_]*(?=[\(\{])/
VALUE: /[^\s·|@.:{}\(\)\n]+/