%import common.NEWLINE
%import common.WS_INLINE

// ─────────────────────────────────────────────
// TOKENs
// ─────────────────────────────────────────────

NAME: /[a-zA-Z_][a-zA-Z0-9_]*/
NUMBER: /-?\d+\/\d+|-?\d*\.\d+|-?\d+/

// SPECIAL CHAR
NOTE: /[a-g](?:\.+|'+)?/
ALEA: /\d+\?/
DEGREE: /\d+(M|m|d|a)/
REPEAT: /x\d+|\d+x\d+/

_NL:    NEWLINE
_DELIM: "·" | "|"
_SEP: WS_INLINE

SYM: /\+|\-|\*|\/|<|>|=|\./

header: "@" NAME ("#" NUMBER)?

?poem: phrase | statement


// ─────────────────────────────────────────────
// MAIN ENTRIEs
// ─────────────────────────────────────────────

statement: header _SEP expr (_SEP expr)*

phrase:  header stanza* _SEP* verses
verses: ((_DELIM | _NL) _SEP* verse _SEP*)+
verse: _SEP* expr (_SEP expr)*

// ─────────────────────────────────────────────
// stanza are modifiers aka FXs
// ─────────────────────────────────────────────

stanza: _NL* (serial | parallel)

serial:   "." NAME array? ("{}"|"()")?
parallel: ":" NAME array? ("{}"|"()")?

// ─────────────────────────────────────────────
// STRUCTURES
// ─────────────────────────────────────────────

array: "(" _SEP* expr (_SEP+ expr)* _SEP* ")"
     | "{" _SEP* expr (_SEP+ expr)* _SEP* "}"

func: NAME array

// ─────────────────────────────────────────────
// LEAVEs
// ─────────────────────────────────────────────

expr: term (SYM term)*

?term: func
     | array
     | NOTE
     | NUMBER
     | NAME
     | ALEA
     | REPEAT
     | DEGREE
