%import common.NEWLINE
%import common.WS_INLINE

// ─────────────────────────────────────────────
// TOKENs
// ─────────────────────────────────────────────

NAME: /[a-zA-Z_][a-zA-Z0-9_]*/
NUMBER: /-?\d+\/\d+|-?\d*\.\d+|-?\d+/

// SPECIAL CHAR
NOTE: /[a-g](?:\.+|'+)?/
ALEA: /\d+\?/
DEGREE: /\d+(M|m|d|a)/
REPEAT: /x\d+|\d+x\d+/

_NL:    NEWLINE
_DELIM: "·" | "|"
_SPACE: WS_INLINE

SYM: /\+|\-|\*|\/|<|>|=|\./

header: "@" NAME ("#" NUMBER)?

?poem: phrase | statement


// ─────────────────────────────────────────────
// MAIN ENTRIEs
// ─────────────────────────────────────────────

statement: header _SPACE expr (_SPACE expr)*

phrase:  header stanza* verses

// ─────────────────────────────────────────────
// VERSE
// ─────────────────────────────────────────────

verses: ((_DELIM | _NL) verse)+
verse: _SPACE* expr (_SPACE expr)*

// ─────────────────────────────────────────────
// stanza are modifiers aka FXs
// ─────────────────────────────────────────────

stanza: _NL* (serial | parallel)

serial:   "." NAME array? ("{}"|"()")?
parallel: ":" NAME array? ("{}"|"()")?

// ─────────────────────────────────────────────
// STRUCTURES
// ─────────────────────────────────────────────

array: "(" _SPACE* expr (_SPACE+ expr)* _SPACE* ")"
     | "{" _SPACE* expr (_SPACE+ expr)* _SPACE* "}"

func: NAME array

// ─────────────────────────────────────────────
// LEAVEs
// ─────────────────────────────────────────────

expr: term (SYM term)*

?term: func
     | array
     | NOTE
     | NUMBER
     | NAME
     | ALEA
     | REPEAT
     | DEGREE
