%import common.NEWLINE
%import common.WS_INLINE

%ignore /;[^\n]*/
%ignore /;@[\s\S]*?$/

_NL:    NEWLINE
_DELIM: "·" | "|"
_SEP: WS_INLINE

// ─── HEADER ──────────────────────────────────────────────────────────────────
id: "#" NUMBER
header: "@" NAME id*

// ─── ENTRY ───────────────────────────────────────────────────────────────────

?unit: phrase | statement

// ─── STATEMENT ───────────────────────────────────────────────────────────────

statement: header _SEP atom+ (_SEP atom+)*

// ─── PHRASE ──────────────────────────────────────────────────────────────────

phrase:  header modifier* _SEP* score
score: ((_DELIM | _NL) _SEP* quality _SEP*)+
quality: _SEP* atom+ (_SEP atom+)*

// ─── MODIFIERS ───────────────────────────────────────────────────────────────

modifier: _NL* (dot_mod | colon_mod)

dot_mod:   "." NAME array?
colon_mod: ":" NAME array?

// ─── ARRAYS ──────────────────────────────────────────────────────────────────

array: "(" _SEP* (atom+ (_SEP+ atom+)*)? _SEP* ")"
     | "{" _SEP* (atom+ (_SEP+ atom+)*)? _SEP* "}"

// ─── ATOM ────────────────────────────────────────────────────────────────────

atom: NAME array -> func
    | array
    | NAME
    | NUMBER
    | SYM

// ─── TOKENS ──────────────────────────────────────────────────────────────────

NAME.3:   /[a-zA-Z_][a-zA-Z0-9_]*/
NUMBER.2: /-?\d+\/\d+|-?\d*\.\d+|-?\d+/
//SYM.1: /[^\s·|@:{}\(\){}\na-zA-Z0-9_\n]+/
SYM.1: /[^\s·|@:{}\(\){}a-zA-Z0-9_\n]+/